### ISSUE TITLE
"compatible with ra-admin" ?

### ISSUE THREAD

**Issue by danysz** [ElegantSoft/go-restful-generator#2]
Hello

Is compatible with "https://www.radmin.com" or you meant with "https://marmelab.com/react-admin/" ?

If it's the second option which "dataProvider" should be used ?

Thanks

Daniel

**Comment by ElegantSoft** [comment]
Please use [https://github.com/FusionWorks/react-admin-nestjsx-crud-dataprovider](nestjsx crud react admin data provider) you may need to change operators from `$eq` to 'eq'

**Comment by danysz** [comment]
hi,

i tried to use it but it didn't work

i will be happy to have a working example

thanks

**Comment by ElegantSoft** [comment]
@danysz I will do that soon

**Comment by ElegantSoft** [comment]
Hello @danysz I am so sorry for late resolve. I updated the repo and added react admin working example.
I hope we help each other to improve this project.
Best wishes.

**Comment by dmchmk** [comment]
Hi, @ElegantSoft, unfortunately, the [link in the README.md](https://github.com/ElegantSoft/go-restful-generator?tab=readme-ov-file#features) still points [to the wrong raadmin](https://www.radmin.com/))

**Comment by shambhu-sharan** [comment]
@ElegantSoft I have connected to the database. Only the post table was added, and a Swagger API for posts was generated. How to generate CRUD for all tables available in the database? This means I want to generate CRUD operations from the database. Is it possible?
